### PR TITLE
211 missing docker port mapping in doc examples

### PR DESCRIPTION
**Pull request by demeringo**
Small doc fixes for #211

### CODE REVIEW

**Comment by da-ekchajzer** [comment]
I am not sure that we should hard code the version in the doc since it will be changing on a regular basis. What do you think ?

**Comment by demeringo** [comment]
> Thanks for the port correction. I am not sure that we should hard code the version in the doc since it will be changing on a regular basis. What do you think ?

It still think it can be usefull for a beginner just wanting to quicly test a local API with docker. My understanding is that mapping a port with the `-p` is mandatory to access the API from outside the container, so I prefer to add it to the doc.

**Comment by da-ekchajzer** [comment]
Of course, for the port. I was talking about the version number.

**Comment by demeringo** [comment]
> Of course, for the port. I was talking about the version number.

;-) ... Still I think we should indicate version number for the time being (at least until we make "latest" tag point to the latest version of main or dev branch). Today a very old version of API is returned with "latest" tag which may confuse a newcommer (and sometimes also an oldcommer like me ;-) ) see #210

**Comment by demeringo** [comment]
@da-ekchajzer please forget my comment about explicit version tag in the docker comment, the underlying issue does not exist !

**Comment by demeringo** [comment]
I will remove the tag from code exemples and update this PR...

**Pull request merged**
